# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
domain: biorob-2022-workshop-upper-limb.github.io
url: 'https://biorob-2022-workshop-upper-limb.github.io'
baseurl: ''
title: 'Closing the Loop on Upper-Limb Assistive Device Design, Sensing, Control, & Clinical Practice'
classes: wide
description: 'Welcome to the BioRob 2022 workshop on Closing the Loop on Upper-Limb Assistive Device Design, Sensing, Control, & Clinical Practice.'
permalink: pretty
logo: '/assets/images/logo.png'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
  classes: wide
- title: About
  url: /about/
  classes: wide
- title: Call for Contributions
  url: /cfp/
  classes: wide
- title: Schedule
  url: /schedule/
  classes: wide
- title: Speakers & Organizers
  url: /speakorg/
  classes: wide
- title: Contact
  url: /contact/
  classes: wide
- title: Sponsors
  url: /sponsors/
  classes: wide

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "/assets/images/banner.png"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
